# SPDX-FileCopyrightText: Copyright (c) 2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Copyright (c) 2021 ETH Zurich, Nikita Rudin


"""Resolved upstream RESUME=False configuration; no simulator imports."""
from copy import deepcopy

UPSTREAM_SHA = "8159e4ed8695b2d3f62a40d2ab8d88205ac5021a"
_PUBLIC_FRESH = {'arm': {'grasp_offset': 0.08,
         'init_target_ee_base': [0.2, 0.0, 0.2],
         'osc_kd': [20.0, 20.0, 20.0, 10.954451150103322, 10.954451150103322, 10.954451150103322],
         'osc_kp': [100, 100, 100, 30, 30, 30]},
 'asset': {'angular_damping': 0.0,
           'armature': 0.0,
           'collapse_fixed_joints': True,
           'default_dof_drive_mode': 3,
           'density': 0.001,
           'disable_gravity': False,
           'file': '{LEGGED_GYM_ROOT_DIR}/resources/robots/widowGo1/urdf/widowGo1.urdf',
           'fix_base_link': False,
           'flip_visual_attachments': False,
           'foot_name': 'foot',
           'linear_damping': 0.0,
           'max_angular_velocity': 1000.0,
           'max_linear_velocity': 1000.0,
           'penalize_contacts_on': ['thigh', 'trunk'],
           'replace_cylinder_with_capsule': True,
           'self_collisions': 0,
           'terminate_after_contacts_on': [],
           'thickness': 0.01},
 'box': {'added_mass_range': [-0.001, 0.05],
         'box_env_origins_x': 0,
         'box_env_origins_y_range': [0.1, 0.3],
         'box_env_origins_z': 0.21000000000000002,
         'box_pos_obs_range': 1.0,
         'box_size': 0.1,
         'randomize_base_mass': True},
 'commands': {'ang_vel_yaw_clip': 0.6,
              'ang_vel_yaw_schedule': [0, 1],
              'curriculum': True,
              'lin_vel_x_clip': 0.3,
              'lin_vel_x_schedule': [0, 1],
              'num_commands': 3,
              'ranges': {'final_ang_vel_yaw': [-1.0, 1.0],
                         'final_lin_vel_x': [0, 0.9],
                         'final_tracking_ang_vel_yaw_exp': 0.15,
                         'init_ang_vel_yaw': [0, 0],
                         'init_lin_vel_x': [0, 0]},
              'resampling_time': 3.0,
              'tracking_ang_vel_yaw_schedule': [0, 1]},
 'control': {'action_scale': [0.4,
                              0.45,
                              0.45,
                              0.4,
                              0.45,
                              0.45,
                              0.4,
                              0.45,
                              0.45,
                              0.4,
                              0.45,
                              0.45,
                              2.1,
                              0.6,
                              0.6,
                              0,
                              0,
                              0],
             'adaptive_arm_gains': False,
             'damping': {'joint': 1, 'widow': 0.5},
             'decimation': 4,
             'stiffness': {'joint': 50, 'widow': 5},
             'torque_supervision': False},
 'domain_rand': {'added_com_range_x': [-0.15, 0.15],
                 'added_com_range_y': [-0.15, 0.15],
                 'added_com_range_z': [-0.15, 0.15],
                 'added_mass_range': [-0.5, 2.5],
                 'arm_motor_strength_range': [0.7, 1.3],
                 'cube_y_range': [0.2, 0.4],
                 'friction_range': [-0.5, 3.0],
                 'gripper_added_mass_range': [0, 0.1],
                 'leg_motor_strength_range': [0.7, 1.3],
                 'max_push_vel_xy': 0.5,
                 'observe_priv': True,
                 'push_interval_s': 3,
                 'push_robots': True,
                 'randomize_base_com': True,
                 'randomize_base_mass': True,
                 'randomize_friction': True,
                 'randomize_gripper_mass': True,
                 'randomize_motor': True},
 'env': {'action_delay': 2,
         'episode_length_s': 10,
         'history_len': 10,
         'num_actions': 18,
         'num_envs': 5000,
         'num_observations': 860,
         'num_priv': 24,
         'num_privileged_obs': None,
         'num_proprio': 76,
         'num_torques': 18,
         'reorder_dofs': True,
         'send_timeouts': True},
 'goal_ee': {'collision_lower_limits': [-0.2, -0.15, -0.515],
             'collision_upper_limits': [0.3, 0.15, -0.115],
             'command_mode': 'sphere',
             'hold_time': [0.5, 2],
             'init_ranges': {'pos_l': [0.3, 0.5],
                             'pos_p': [0.7853981633974483, 2.356194490192345],
                             'pos_y': [0, 0]},
             'l_schedule': [0, 1],
             'num_collision_check_samples': 10,
             'num_commands': 3,
             'orn_error_scale': [0.6366197723675814, 0.6366197723675814, 0.6366197723675814],
             'p_schedule': [0, 1],
             'ranges': {'final_delta_orn': [[0, 0], [0, 0], [0, 0]],
                        'final_pos_l': [0.2, 0.7],
                        'final_pos_p': [-1.2566370614359172, 0.6283185307179586],
                        'final_pos_y': [-1.8849555921538759, 1.8849555921538759],
                        'final_tracking_ee_reward': 0.55,
                        'init_pos_l': [0.6, 0.6],
                        'init_pos_p': [0.7853981633974483, 0.7853981633974483],
                        'init_pos_y': [-0.5235987755982988, 0.5235987755982988]},
             'sphere_error_scale': [2.0000000000000004, 0.5305164769729844, 0.2652582384864922],
             'tracking_ee_reward_schedule': [0, 1],
             'traj_time': [1, 3],
             'underground_limit': -0.57,
             'y_schedule': [0, 1]},
 'init_state': {'ang_vel': [0.0, 0.0, 0.0],
                'default_joint_angles': {'FL_hip_joint': 0.1,
                                         'FL_thigh_joint': 0.8,
                                         'FL_calf_joint': -1.5,
                                         'RL_hip_joint': 0.1,
                                         'RL_thigh_joint': 0.8,
                                         'RL_calf_joint': -1.5,
                                         'FR_hip_joint': -0.1,
                                         'FR_thigh_joint': 0.8,
                                         'FR_calf_joint': -1.5,
                                         'RR_hip_joint': -0.1,
                                         'RR_thigh_joint': 0.8,
                                         'RR_calf_joint': -1.5,
                                         'widow_waist': 0,
                                         'widow_shoulder': 0,
                                         'widow_elbow': 0,
                                         'widow_wrist_angle': 0,
                                         'widow_forearm_roll': 0,
                                         'widow_wrist_rotate': 0,
                                         'widow_left_finger': 0,
                                         'widow_right_finger': 0},
                'lin_vel': [0.0, 0.0, 0.0],
                'pos': [0.0, 0.0, 0.42],
                'rot': [0.0, 0.0, 0.0, 1.0]},
 'noise': {'add_noise': False,
           'noise_level': 1.0,
           'noise_scales': {'ang_vel': 0.2,
                            'dof_pos': 0.01,
                            'dof_vel': 1.5,
                            'gravity': 0.05,
                            'height_measurements': 0.1,
                            'lin_vel': 0.1}},
 'normalization': {'clip_actions': 100.0,
                   'clip_observations': 100.0,
                   'obs_scales': {'ang_vel': 1.0,
                                  'dof_pos': 1.0,
                                  'dof_vel': 0.05,
                                  'height_measurements': 5.0,
                                  'lin_vel': 1.0}},
 'rewards': {'arm_scales': {'arm_energy_abs_sum': -0.004,
                            'arm_orientation': -0.0,
                            'termination': -0.0,
                            'tracking_ee_cart': 0.0,
                            'tracking_ee_orn': 0.0,
                            'tracking_ee_orn_ry': 0.0,
                            'tracking_ee_sphere': 0.55},
             'base_height_target': 0.25,
             'max_contact_force': 100.0,
             'only_positive_rewards': False,
             'scales': {'action_rate': 0,
                        'ang_vel_xy': -0.0,
                        'base_height': 0,
                        'collision': 0,
                        'dof_acc': 0,
                        'dof_vel': 0,
                        'energy_square': -6e-05,
                        'feet_air_time': 0,
                        'feet_stumble': 0,
                        'foot_contacts_z': -0.0001,
                        'hip_action_l2': -0.01,
                        'leg_action_l2': -0.0,
                        'leg_energy': 0,
                        'leg_energy_abs_sum': 0,
                        'lin_vel_z': -0.0,
                        'orientation': -0.0,
                        'stand_still': 0,
                        'survive': 0.2,
                        'termination': 0,
                        'torques': 0,
                        'tracking_ang_vel': 0.0,
                        'tracking_ang_vel_yaw_exp': 0.15,
                        'tracking_ang_vel_yaw_l1': 0,
                        'tracking_lin_vel': 0.0,
                        'tracking_lin_vel_x_exp': 0.0,
                        'tracking_lin_vel_x_l1': 0.5,
                        'tracking_lin_vel_y_l2': 0,
                        'tracking_lin_vel_z_l2': -0.0},
             'soft_dof_pos_limit': 1.0,
             'soft_dof_vel_limit': 1.0,
             'soft_torque_limit': 1.0,
             'tracking_ee_sigma': 1,
             'tracking_sigma': 1},
 'sim': {'dt': 0.005,
         'gravity': [0.0, 0.0, -9.81],
         'physx': {'bounce_threshold_velocity': 0.5,
                   'contact_collection': 2,
                   'contact_offset': 0.01,
                   'default_buffer_size_multiplier': 5,
                   'max_depenetration_velocity': 1.0,
                   'max_gpu_contact_pairs': 8388608,
                   'num_position_iterations': 4,
                   'num_threads': 10,
                   'num_velocity_iterations': 0,
                   'rest_offset': 0.0,
                   'solver_type': 1},
         'substeps': 1,
         'up_axis': 1},
 'termination': {'p_threshold': 0.6, 'r_threshold': 0.78, 'z_threshold': 0.325},
 'terrain': {'add_slopes': True,
             'border_size': 0,
             'curriculum': False,
             'dynamic_friction': 1.0,
             'horizontal_scale': 0.025,
             'init_vel_perturb_range': 0.1,
             'measure_heights': False,
             'measured_points_x': [-0.8,
                                   -0.7,
                                   -0.6,
                                   -0.5,
                                   -0.4,
                                   -0.3,
                                   -0.2,
                                   -0.1,
                                   0.0,
                                   0.1,
                                   0.2,
                                   0.3,
                                   0.4,
                                   0.5,
                                   0.6,
                                   0.7,
                                   0.8],
             'measured_points_y': [-0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5],
             'mesh_type': 'trimesh',
             'origin_perturb_range': 0.5,
             'restitution': 0.0,
             'slope_incline': 0.2,
             'slope_treshold': 100000000,
             'static_friction': 1.0,
             'tot_cols': 600,
             'tot_rows': 10000,
             'transform_x': -7.5,
             'transform_y': -125.0,
             'transform_z': 0.0,
             'vertical_scale': 1e-05,
             'zScale': 0.15},
 'viewer': {'lookat': [0, 0, -2], 'pos': [-20, 0, 20]},
 'algorithm': {'adaptive_arm_gains': False,
               'clip_param': 0.2,
               'dagger_update_freq': 20,
               'desired_kl': None,
               'entropy_coef': 0.0,
               'gamma': 0.99,
               'lam': 0.95,
               'learning_rate': 0.0002,
               'max_grad_norm': 1.0,
               'min_policy_std': [[0.15,
                                   0.25,
                                   0.25,
                                   0.15,
                                   0.25,
                                   0.25,
                                   0.15,
                                   0.25,
                                   0.25,
                                   0.15,
                                   0.25,
                                   0.25,
                                   0.2,
                                   0.2,
                                   0.2,
                                   0.05,
                                   0.05,
                                   0.05]],
               'mixing_schedule': [1.0, 0, 3000],
               'num_learning_epochs': 5,
               'num_mini_batches': 4,
               'priv_reg_coef_schedual': [0, 0.1, 3000, 7000],
               'schedule': 'fixed',
               'torque_supervision': False,
               'torque_supervision_schedule': [0.0, 1000, 1000],
               'use_clipped_value_loss': True,
               'value_loss_coef': 1.0},
 'policy': {'activation': 'elu',
            'actor_hidden_dims': [128],
            'adaptive_arm_gains': False,
            'adaptive_arm_gains_scale': 10.0,
            'arm_control_head_hidden_dims': [128, 128],
            'critic_hidden_dims': [128],
            'init_std': [[0.8,
                          1.0,
                          1.0,
                          0.8,
                          1.0,
                          1.0,
                          0.8,
                          1.0,
                          1.0,
                          0.8,
                          1.0,
                          1.0,
                          1.0,
                          1.0,
                          1.0,
                          1.0,
                          1.0,
                          1.0]],
            'leg_control_head_hidden_dims': [128, 128],
            'num_arm_actions': 6,
            'num_leg_actions': 12,
            'priv_encoder_dims': [64, 20]},
 'runner': {'algorithm_class_name': 'PPO',
            'checkpoint': -1,
            'experiment_name': 'rough_widowGo1',
            'load_run': -1,
            'max_iterations': 40000,
            'num_steps_per_env': 40,
            'policy_class_name': 'ActorCritic',
            'resume': False,
            'resume_path': None,
            'run_name': '',
            'save_interval': 500},
 'runner_class_name': 'OnPolicyRunner',
 'seed': 1}

def default_config(schedule="public_fresh"):
    """Public fresh recipe, or documented paper budget/regularization override.

    Both retain the public position-only task and its 15 nonzero target channels.
    The paper option is not a claim of full paper 6D reproduction.
    """
    if schedule not in ("public_fresh", "paper"):
        raise ValueError(f"Unknown DeepWBC schedule: {schedule}")
    cfg = deepcopy(_PUBLIC_FRESH)
    if schedule == "paper":
        cfg["runner"]["max_iterations"] = 10000
        cfg["algorithm"]["priv_reg_coef_schedual"] = [0, 1, 5000, 5000]
    return cfg
